[tls.stores.default.defaultCertificate]
certFile = "/data/ssl/{{domain}}.pem.crt"
keyFile = "/data/ssl/{{domain}}.pem.key"

[[tls.certificates]]
certFile = "/data/ssl/{{domain}}.pem.crt"
keyFile = "/data/ssl/{{domain}}.pem.key"
