[tcp.routers.postgres]
entryPoints = ["postgres"]
rule = "HostSNI(`*`)"
service = "postgres"

[tcp.services.postgres.loadBalancer]
[[tcp.services.postgres.loadBalancer.servers]]
address = "postgres:5432"
