# Garage configuration
# Reference: https://garagehq.deuxfleurs.fr/documentation/reference-manual/configuration/

replication_factor = 1

metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
metadata_auto_snapshot_interval = "6h"
db_engine = "lmdb"

rpc_bind_addr = "[::]:3901"
rpc_secret_file = "/var/lib/garage/meta/.rpc_secret"

[s3_api]
api_bind_addr = "[::]:3900"
s3_region = "garage"
root_domain = ".s3.garage"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage"

[admin]
api_bind_addr = "[::]:3903"
