[traefik.files]
traefik = '~/.config'

[traefik.files.'traefik/traefik']
target = '~/.config/traefik'
type = 'template'

[postgres.files]
postgres = '~/.config'

[garage.files]
garage = '~/.config'

[garage.files.'garage/garage']
target = '~/.config/garage'
type = 'template'

[silverbullet.files]
silverbullet = '~/.config'

[langfuse.files]
langfuse = '~/.config'

[dozzle.files]
dozzle = '~/.config'

[omnivore.files]
omnivore = '~/.config'

[plane.files]
plane = '~/.config'

[copyparty.files]
copyparty = '~/.config'

[marimo.files]
marimo = '~/.config'
